services:
  - type: web
    name: customer-churn-prediction
    env: python
    plan: free

    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
